#cloud-config
package_update: true
package_upgrade: true

packages:
  - git
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

groups:
  - docker, sudo

users:
 - name: ubuntu
 - groups: docker, admin, sudo

system_info:
  default_user:
    groups: [docker, sudo, admin]
    name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL

runcmd:
  - sudo usermod -aG sudo $USER
  - sudo usermod -aG docker $USER
  - sudo id $USER
  - sudo hostnamectl set-hostname APPLICATION-BACKEND
  # install docker following the guide: https://docs.docker.com/install/linux/docker-ce/ubuntu/
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get -y update
  - sudo apt-get -y install docker-ce docker-ce-cli containerd.io
  - sudo systemctl enable docker
  - sudo systemctl start docker.service
  - sudo id $USER
  - touch /tmp/signal



final_message: "The system is finally up, after $UPTIME seconds"




